const todoData = [
    {
        id: 1,
        title: "Go bungee jumping",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        description: " No Description",
        assigned: "Aya",
        done: false,
    },
    {
        id: 2,
        title: "Go bungee jumping",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        description: " No Description",
        assigned: "Hussain",
        done: false,
    },
    {
        id: 3,
        title: "Learn to paint a picture",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        description: " No Description",
        assigned: "Hussain",
        done: false,
    },
    {
        id: 4,
        title: "Write a book",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        description: " No Description",
        assigned: "Aya",
        done: false,
    },
    {
        id: 5,
        title: "Travel to every continent",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        description: " No Description",
        assigned: "Aya",
        done: false,
    },
    {
        id: 6,
        title: "Skydive from a plane",
        startDate: "2024-01-01",
        endDate: "2024-01-31",
        description: " No Description",
        assigned: "Hussain",
        done: false,
    },
];

export default todoData;
